[project]
name = "infectious-disease-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "feedparser>=6.0.12",
    "lxml>=6.1.0",
    "pandas>=3.0.3",
    "plotly>=6.7.0",
    "pycountry>=26.2.16",
    "requests>=2.34.2",
    "streamlit>=1.57.0",
]
